name: Simple Echo Workflow


on: worflow_dispatch

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello from GitHub Actions!"
      - name: Print another message
        run: echo "Hello from GitHub Actions!"
